positions:
  target_1: [-32.114, 630.832, 676.49, 136.729, 16.1, 15.115]
  target_2: [5.461, 675.568, 743.761, -147.934, -9.003, 14.025]
  greet: [0, 630.832, 676.49, 180, 0, 20]
  story: [ 13.347, 540.737, 741.392, -27.172, -11.204, -23.275 ]
  gift_joint_release : [-400.387, 574.934, 713.491, -145.941, -12.938, 55.855]

joint:
  cycle_joint_init: [77.551, 33.982, 108.137, -141.045, -20.051, 32.783]
  gift_joint_init : [92.223, -31.616, 44.008, 5.012, 149.835, -106.034]
  gift_joint_release : [123.957, -29.628, 33.329, 1.945, 84.189, -115.6349]
  greet_joint_init: [88.796, 5.049, 111.603, 0, -77.333, -114.763]
  greet_joint_left: [88.795, 5.049, 111.603, -25.358, -77.334, -114.763]
  greet_joint_right: [88.795, 5.049, 111.603, 25.358, -77.334, -114.763]

